services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./configs/loki/loki-config.yaml:/etc/loki/config.yaml:ro
      - loki_data:/loki
    ports:
      - "3100:3100"
    networks:
      - monitoring

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: ["-config.file=/etc/tempo/config.yaml", "-config.expand-env=true"]
    volumes:
      - ./configs/tempo/tempo-config.yaml:/etc/tempo/config.yaml:ro
      - tempo_data:/var/tempo
    ports:
      - "3200:3200"
    networks:
      - monitoring

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    command: ["-config.file=/etc/mimir/config.yaml", "-querier.query-engine=prometheus"]
    volumes:
      - ./configs/mimir/mimir-config.yaml:/etc/mimir/config.yaml:ro
      - mimir_data:/data
      - mimir_ruler_data:/data/ruler
    ports:
      - "9009:9009"
    networks:
      - monitoring

  pyroscope:
    image: grafana/pyroscope:latest
    container_name: pyroscope
    command: ["-config.file=/etc/pyroscope/config.yaml"]
    volumes:
      - ./configs/pyroscope/pyroscope-config.yaml:/etc/pyroscope/config.yaml:ro
      - pyroscope_data:/var/lib/pyroscope
    ports:
      - "4040:4040"
    networks:
      - monitoring

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    volumes:
      - ./configs/alloy/alloy.alloy:/etc/alloy/config.alloy:ro
      - alloy_data:/var/lib/alloy/data
    ports:
      - "12345:12345"
      - "4317:4317"
      - "4318:4318"
      - "12347:12347"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_USERS_DEFAULT_THEME: light
      GF_SERVER_ROOT_URL: "http://localhost:3000"
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    volumes:
      - ./configs/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./configs/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring
    driver: bridge

volumes:
  loki_data:
  tempo_data:
  mimir_data:
  mimir_ruler_data:
  pyroscope_data:
  alloy_data:
  alertmanager_data:
  grafana_data:
