global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'otel-collector:8889'

  - job_name: 'containeradvisor'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'cadvisor:8080' ]

  - job_name: 'laravel_app'
    scrape_interval: 15s
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'app:80' ]

  - job_name: 'go_app'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'go-app:8080' ]