apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://victoriametrics:8428
    access: proxy
    isDefault: true

  - name: Tempo
    type: tempo
    url: http://tempo:3200
    access: proxy

  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy

  - name: Jaeger
    type: jaeger
    url: http://jaeger:16686
    access: proxy