#stream_over_http_enabled: true
server:
  http_listen_port: 3200  # Tempo's web UI port
  grpc_listen_port: 9095  # Tempo's OTLP gRPC endpoint for traces

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"  # OTLP gRPC endpoint (should match OTEL Collector's gRPC endpoint)
        http:
          endpoint: "0.0.0.0:4318"  # OTLP HTTP endpoint (should match OTEL Collector's HTTP endpoint)

query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
    metadata_slo:
      duration_slo: 5s
      throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 48h  # Retain traces for 48 hours

storage:
  trace:
    backend: local
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/blocks

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
#      cluster: linux-microservices
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://victoriametrics:9090/api/v1/write
        send_exemplars: true
  traces_storage:
    path: /var/tempo/generator/traces

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks]
      generate_native_histograms: both